Add plotting functions.
platiagro/sdk pull request #60
Opened 2020-11-25 16:52 UTC by lucaslzl

2020-11-25 17:16 UTC, fberanizo requested changes
@lucaslzl Parece tudo bonito (só precisa alterar aquele camelCase).
E poderia ter um arquivo de teste também:
https://github.com/platiagro/sdk/tree/master/tests

Mas se estiver na correria td bem :)

2020-11-25 17:16 UTC, fberanizo commented on platiagro/plotting.py
> +    cellText = [
@lucaslzl o sonar acusou uma variável camelCase aqui. É melhor renomeá-la.
https://sonarcloud.io/project/issues?id=platiagro_sdk&open=AXYAVRfWkGmdwVDrNpk7&pullRequest=60&resolved=false&types=CODE_SMELL

2020-11-26 12:12 UTC, lucaslzl commented
Eu vou fazer o arquivo de teste.

2020-12-02 15:49 UTC, fberanizo approved these changes
💯 
:))

2020-12-02 15:49 UTC, merged