changed saving of figures from random to sequential.
platiagro/sdk pull request #85
Opened 2021-04-19 21:04 UTC by dnlcesilva

Changed saving of figures from random to sequential in the figures.py file in the save_figure() function.

2021-04-20 16:47 UTC, fberanizo requested changes

2021-04-20 16:47 UTC, fberanizo commented on platiagro/figures.py
> +    seq = iter(range(1, 100))
@dnlcesilva acho que o id `seq = iter(range(1, 100))` não vai funcionar da forma esperada.
O comportamento que queremos implementar é algo assim:

```python
img1_base64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII"
save_figure(img1_base64, extension="png") # salva figura 1

img2_base64 = "R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
save_figure(img2_base64, extension="gif") # salva figura 2

list_figures()
[
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII",
"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
]
```

Me parece que a cada uso do `save_figure`, da  forma que foi implementado, irá retornar 1 figura, pois o `next(seq)` sempre será "1".

Uma sugestão que pensei aqui é usar um timestamp/data no formato YYYYMMDDHHmmSSsss, que mantem a ordem crescente.

@miguelfferraz o que você acha?

2021-04-20 17:02 UTC, dnlcesilva commented on platiagro/figures.py
> +    seq = iter(range(1, 100))
Entendi, estava imaginando uma sequencia de figuras, mas com timestamp funciona sim.

2021-04-21 19:27 UTC, fberanizo requested changes
@dnlcesilva uma coisa que fiquei em dúvida é se o `list_figures` já retorna as figuras em ordem crescente (de nome do arquivo/data de salvamento). 
Verifique por favor se isso acontece: faça alguns `save_figure` e `list_figures` e veja se a ordem dos items é a mesma que você salvou.

2021-04-21 19:27 UTC, fberanizo commented on platiagro/figures.py
> +    pref = datetime.now().strftime("%y%m%d%H%M%S")
@dnlcesilva testei essa alteração rodando um experimento na máquina .118. 
Parece que será preciso utilizar microsegundos no strftime (`strftime("%Y%m%d%H%M%S%f")`). Houve 2 chamadas no mesmo segundo, as figuras foram sobrescritas e na hora de listar havia menos figuras que o esperado.

2021-04-22 13:16 UTC, dnlcesilva commented on platiagro/figures.py
> +    pref = datetime.now().strftime("%y%m%d%H%M%S")
@fberanizo Add os microsegundos.

2021-04-22 21:12 UTC, fberanizo requested changes

2021-04-22 21:12 UTC, fberanizo commented on platiagro/figures.py
> +    return sorted(figures)
@dnlcesilva este `sorted(figures)` vai ordenar pelo base64 da imagem, e não pelo nome salvo (`object_name`), como deveria ser.
Parece que o list_object_v2 já traz os itens ordenados: https://github.com/minio/minio-py/issues/775

2021-04-22 22:33 UTC, dnlcesilva commented on platiagro/figures.py
> +    return sorted(figures)
@fberanizo vou retirar!

2021-04-23 11:58 UTC, fberanizo approved these changes
👍

2021-04-23 12:03 UTC, merged