Creation of API to create task.
platiagro/sdk pull request #87
Opened 2021-05-11 15:21 UTC by dnlcesilva

Creation of API to create task.

2021-05-13 17:23 UTC, fberanizo requested changes
@dnlcesilva, se lembre de ao abrir o PR conferir o checklist e a análise do sonar:
https://github.com/platiagro/sdk/pull/87#issuecomment-838672884
https://github.com/platiagro/sdk/pull/87#issuecomment-839201283

O `create_task` precisa ser adicionado aos docs do SDK em:
https://github.com/platiagro/sdk/blob/master/docs/source/platiagro.rst

Depois você precisa fazer o build do HTML
```bash
pip install sphinx
cd docs/
make html
rm -r _static/ _sources/
mv build/html/* .
```

Aí a documentação será atualizada no site:
https://platiagro.github.io/sdk/

2021-05-14 10:14 UTC, dnlcesilva commented on platiagro/tasks.py
> +                is_default: Optional[bool] = None):
@fberanizo adicionado.

2021-05-14 10:14 UTC, dnlcesilva commented on platiagro/tasks.py
> +                is_default: Optional[bool] = None):
@fberanizo corrigido.

2021-05-14 12:54 UTC, fberanizo requested changes
@dnlcesilva está quase ok. Tem +2 melhorias:

2021-05-14 12:54 UTC, fberanizo commented on platiagro/tasks.py
> +            "is_default": is_default
@dnlcesilva a interface da API REST é camelCase, então as chaves (str) deste dict tem que ser `"cpuLimit"` `"cpuRequest"` `"memoryLimit"` `"memoryRequest"` `"isDefault"`. As variáveis devem continuar snake_case.

2021-05-14 12:54 UTC, fberanizo commented on platiagro/tasks.py
> +    response = requests.post(url=f"{PROJECTS_ENDPOINT}/tasks", data=json.dumps(data))
Aqui você pode passar `json=data` no lugar de `data=json.dumps(data))` isso já vai adicionar o header `"content-type: application/json"` que está faltando.
Veja o último exemplo desta seção: https://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests

2021-05-14 16:42 UTC, dnlcesilva commented on platiagro/tasks.py
> +            "is_default": is_default
@fberanizo alterado.

2021-05-14 16:42 UTC, dnlcesilva commented on platiagro/tasks.py
> +    response = requests.post(url=f"{PROJECTS_ENDPOINT}/tasks", data=json.dumps(data))
@fberanizo alterado.

2021-05-14 18:19 UTC, fberanizo approved these changes

2021-05-14 18:19 UTC, merged