API to runs deployments
platiagro/sdk pull request #88
Opened 2021-05-14 20:26 UTC by dnlcesilva

Created functions to search for project_id, deployment_id to execute deployments.

2021-05-17 17:26 UTC, fberanizo requested changes

2021-05-17 17:26 UTC, fberanizo commented on platiagro/util.py
> +PROJECTS_ENDPOINT = getenv("PROJECTS_ENDPOINT", "https://projects.platiagro:8080")
@dnlcesilva acho que é melhor deixar `http` (no lugar de https) porque é o padrão da API. O sonar irá reclamar, mas a esse é um alarme que a gente pode ignorar.

2021-05-17 17:26 UTC, fberanizo commented on platiagro/deployments.py
> +    return response.json()
@dnlcesilva `response.json()` é um `dict` (diferente da documentação `requests.Response:`). 
Acho que é importante manter um padrão entre os retornos das funções (todas retornam dict ou todas retornam requests.Response).
Minha sugestão é retornar o `request.Response` sem o .json() mesmo.

2021-05-17 17:26 UTC, fberanizo commented on platiagro/deployments.py
> +def get_deployment_name(project_name: str, deployment_name: str):
@dnlcesilva acho que fica mais legal deixar `get_deployment_by_name` (com o by_). Fica mais claro na leitura da função.

2021-05-17 17:26 UTC, fberanizo commented on platiagro/deployments.py
> +def get_project_name(project_name: str):
@dnlcesilva acho que fica mais legal deixar `get_project_by_name` (com o by_). Fica mais claro na leitura da função.

2021-05-17 17:26 UTC, fberanizo commented on tests/test_deployments.py
> +    @mock.patch("platiagro.deployments.requests.get")
Aqui você vai alterar pra `platiagro.deployments.requests.post` né?

2021-05-17 17:58 UTC, dnlcesilva commented on platiagro/util.py
> +PROJECTS_ENDPOINT = getenv("PROJECTS_ENDPOINT", "https://projects.platiagro:8080")
@fberanizo alterado

2021-05-18 17:32 UTC, fberanizo requested changes

2021-05-18 17:32 UTC, fberanizo commented on tests/test_deployments.py
> +        self.assertEqual(response.status_code, 200)
@dnlcesilva aqui neste teste tem que chamar o `run_deployment` (e não acionar a API diretamente).

2021-05-18 17:53 UTC, dnlcesilva commented on tests/test_deployments.py
> +        self.assertEqual(response.status_code, 200)
@fberanizo isso é o que estava tentando com o @miguelfferraz .

2021-05-18 23:41 UTC, miguelfferraz approved these changes
LGTM

2021-05-18 23:42 UTC, merged